package it.asansonne.storybe.constants;

import lombok.Getter;

@Getter
public enum CountryNames {
    NAME_ANDORRA_PRINCIPALITY_OF("Andorra, Principality Of"),
    NAME_UNITED_ARAB_EMIRATES("United Arab Emirates"),
    NAME_AFGHANISTAN_ISLAMIC_STATE_OF("Afghanistan, Islamic State Of"),
    NAME_ANTIGUA_AND_BARBUDA("Antigua And Barbuda"),
    NAME_ANGUILLA("Anguilla"),
    NAME_ALBANIA("Albania"),
    NAME_ARMENIA("Armenia"),
    NAME_NETHERLANDS_ANTILLES("Netherlands Antilles"),
    NAME_ANGOLA("Angola"),
    NAME_ANTARCTICA("Antarctica"),
    NAME_ARGENTINA("Argentina"),
    NAME_AMERICAN_SAMOA("American Samoa"),
    NAME_AUSTRIA("Austria"),
    NAME_AUSTRALIA("Australia"),
    NAME_ARUBA("Aruba"),
    NAME_AZERBAIDJAN("Azerbaidjan"),
    NAME_BOSNIA_HERZEGOVINA("Bosnia-Herzegovina"),
    NAME_BARBADOS("Barbados"),
    NAME_BANGLADESH("Bangladesh"),
    NAME_BELGIUM("Belgium"),
    NAME_BURKINA_FASO("Burkina Faso"),
    NAME_BULGARIA("Bulgaria"),
    NAME_BAHRAIN("Bahrain"),
    NAME_BURUNDI("Burundi"),
    NAME_BENIN("Benin"),
    NAME_BERMUDA("Bermuda"),
    NAME_BRUNEI_DARUSSALAM("Brunei Darussalam"),
    NAME_BOLIVIA("Bolivia"),
    NAME_BRAZIL("Brazil"),
    NAME_BAHAMAS("Bahamas"),
    NAME_BHUTAN("Bhutan"),
    NAME_BOUVET_ISLAND("Bouvet Island"),
    NAME_BOTSWANA("Botswana"),
    NAME_BELARUS("Belarus"),
    NAME_BELIZE("Belize"),
    NAME_CANADA("Canada"),
    NAME_COCOS_KEELING_ISLANDS("Cocos (Keeling) Islands"),
    NAME_CENTRAL_AFRICAN_REPUBLIC("Central African Republic"),
    NAME_CONGO_DEMOCRATIC_REPUBLIC_OF_THE("Congo, The Democratic Republic Of The"),
    NAME_CONGO("Congo"),
    NAME_SWITZERLAND("Switzerland"),
    NAME_IVORY_COAST_COTE_D_IVOIRE("Ivory Coast (Cote D'Ivoire)"),
    NAME_COOK_ISLANDS("Cook Islands"),
    NAME_CHILE("Chile"),
    NAME_CAMEROON("Cameroon"),
    NAME_CHINA("China"),
    NAME_COLOMBIA("Colombia"),
    NAME_COSTA_RICA("Costa Rica"),
    NAME_FORMER_CZECHOSLOVAKIA("Former Czechoslovakia"),
    NAME_CUBA("Cuba"),
    NAME_CAPE_VERDE("Cape Verde"),
    NAME_CHRISTMAS_ISLAND("Christmas Island"),
    NAME_CYPRUS("Cyprus"),
    NAME_CZECH_REPUBLIC("Czech Republic"),
    NAME_GERMANY("Germany"),
    NAME_DJIBOUTI("Djibouti"),
    NAME_DENMARK("Denmark"),
    NAME_DOMINICA("Dominica"),
    NAME_DOMINICAN_REPUBLIC("Dominican Republic"),
    NAME_ALGERIA("Algeria"),
    NAME_ECUADOR("Ecuador"),
    NAME_ESTONIA("Estonia"),
    NAME_EGYPT("Egypt"),
    NAME_WESTERN_SAHARA("Western Sahara"),
    NAME_ERITREA("Eritrea"),
    NAME_SPAIN("Spain"),
    NAME_ETHIOPIA("Ethiopia"),
    NAME_FINLAND("Finland"),
    NAME_FIJI("Fiji"),
    NAME_FALKLAND_ISLANDS("Falkland Islands"),
    NAME_MICRONESIA("Micronesia"),
    NAME_FAROE_ISLANDS("Faroe Islands"),
    NAME_FRANCE("France"),
    NAME_FRANCE_EUROPEAN_TERRITORY("France (European Territory)"),
    NAME_GABON("Gabon"),
    NAME_GREAT_BRITAIN("Great Britain"),
    NAME_GRENADA("Grenada"),
    NAME_GEORGIA("Georgia"),
    NAME_FRENCH_GUYANA("French Guyana"),
    NAME_GHANA("Ghana"),
    NAME_GIBRALTAR("Gibraltar"),
    NAME_GREENLAND("Greenland"),
    NAME_GAMBIA("Gambia"),
    NAME_GUINEA("Guinea"),
    NAME_GUADELOUPE_FRENCH("Guadeloupe (French)"),
    NAME_EQUATORIAL_GUINEA("Equatorial Guinea"),
    NAME_GREECE("Greece"),
    NAME_S_GEORGIA_S_SANDWICH_ISLS("S. Georgia & S. Sandwich Isls."),
    NAME_GUATEMALA("Guatemala"),
    NAME_GUAM_USA("Guam (USA)"),
    NAME_GUINEA_BISSAU("Guinea Bissau"),
    NAME_GUYANA("Guyana"),
    NAME_HONG_KONG("Hong Kong"),
    NAME_HEARD_AND_MCDONALD_ISLANDS("Heard And McDonald Islands"),
    NAME_HONDURAS("Honduras"),
    NAME_CROATIA("Croatia"),
    NAME_HAITI("Haiti"),
    NAME_HUNGARY("Hungary"),
    NAME_INDONESIA("Indonesia"),
    NAME_IRELAND("Ireland"),
    NAME_ISRAEL("Israel"),
    NAME_INDIA("India"),
    NAME_BRITISH_INDIAN_OCEAN_TERRITORY("British Indian Ocean Territory"),
    NAME_IRAQ("Iraq"),
    NAME_IRAN("Iran"),
    NAME_ICELAND("Iceland"),
    NAME_ITALY("Italy"),
    NAME_JAMAICA("Jamaica"),
    NAME_JORDAN("Jordan"),
    NAME_JAPAN("Japan"),
    NAME_KENYA("Kenya"),
    NAME_KYRGYZ_REPUBLIC_KYRGYZSTAN("Kyrgyz Republic (Kyrgyzstan)"),
    NAME_CAMBODIA_KINGDOM_OF("Cambodia, Kingdom Of"),
    NAME_KIRIBATI("Kiribati"),
    NAME_COMOROS("Comoros"),
    NAME_SAINT_KITTS_NEVIS_ANGUILLA("Saint Kitts & Nevis Anguilla"),
    NAME_NORTH_KOREA("North Korea"),
    NAME_SOUTH_KOREA("South Korea"),
    NAME_KUWAIT("Kuwait"),
    NAME_CAYMAN_ISLANDS("Cayman Islands"),
    NAME_KAZAKHSTAN("Kazakhstan"),
    NAME_LAOS("Laos"),
    NAME_LEBANON("Lebanon"),
    NAME_SAINT_LUCIA("Saint Lucia"),
    NAME_LIECHTENSTEIN("Liechtenstein"),
    NAME_SRI_LANKA("Sri Lanka"),
    NAME_LIBERIA("Liberia"),
    NAME_LESOTHO("Lesotho"),
    NAME_LITHUANIA("Lithuania"),
    NAME_LUXEMBOURG("Luxembourg"),
    NAME_LATVIA("Latvia"),
    NAME_LIBYA("Libya"),
    NAME_MOROCCO("Morocco"),
    NAME_MONACO("Monaco"),
    NAME_MOLDAVIA("Moldavia"),
    NAME_MADAGASCAR("Madagascar"),
    NAME_MARSHALL_ISLANDS("Marshall Islands"),
    NAME_MACEDONIA("Macedonia"),
    NAME_MALI("Mali"),
    NAME_MYANMAR("Myanmar"),
    NAME_MONGOLIA("Mongolia"),
    NAME_MACAU("Macau"),
    NAME_NORTHERN_MARIANA_ISLANDS("Northern Mariana Islands"),
    NAME_MARTINIQUE_FRENCH("Martinique (French)"),
    NAME_MAURITANIA("Mauritania"),
    NAME_MONTSERRAT("Montserrat"),
    NAME_MALTA("Malta"),
    NAME_MAURITIUS("Mauritius"),
    NAME_MALDIVES("Maldives"),
    NAME_MALAWI("Malawi"),
    NAME_MEXICO("Mexico"),
    NAME_MALAYSIA("Malaysia"),
    NAME_MOZAMBIQUE("Mozambique"),
    NAME_NAMIBIA("Namibia"),
    NAME_NEW_CALEDONIA_FRENCH("New Caledonia (French)"),
    NAME_NIGER("Niger"),
    NAME_NORFOLK_ISLAND("Norfolk Island"),
    NAME_NIGERIA("Nigeria"),
    NAME_NICARAGUA("Nicaragua"),
    NAME_NETHERLANDS("Netherlands"),
    NAME_NORWAY("Norway"),
    NAME_NEPAL("Nepal"),
    NAME_NAURU("Nauru"),
    NAME_NEUTRAL_ZONE("Neutral Zone"),
    NAME_NIUE("Niue"),
    NAME_NEW_ZEALAND("New Zealand"),
    NAME_OMAN("Oman"),
    NAME_PANAMA("Panama"),
    NAME_PERU("Peru"),
    NAME_POLYNESIA_FRENCH("Polynesia (French)"),
    NAME_PAPUA_NEW_GUINEA("Papua New Guinea"),
    NAME_PHILIPPINES("Philippines"),
    NAME_PAKISTAN("Pakistan"),
    NAME_POLAND("Poland"),
    NAME_SAINT_PIERRE_AND_MIQUELON("Saint Pierre And Miquelon"),
    NAME_PITCAIRN_ISLAND("Pitcairn Island"),
    NAME_PUERTO_RICO("Puerto Rico"),
    NAME_PORTUGAL("Portugal"),
    NAME_PALAU("Palau"),
    NAME_PARAGUAY("Paraguay"),
    NAME_QATAR("Qatar"),
    NAME_REUNION_FRENCH("Reunion (French)"),
    NAME_ROMANIA("Romania"),
    NAME_RUSSIAN_FEDERATION("Russian Federation"),
    NAME_RWANDA("Rwanda"),
    NAME_SAUDI_ARABIA("Saudi Arabia"),
    NAME_SOLOMON_ISLANDS("Solomon Islands"),
    NAME_SEYCHELLES("Seychelles"),
    NAME_SUDAN("Sudan"),
    NAME_SWEDEN("Sweden"),
    NAME_SINGAPORE("Singapore"),
    NAME_SAINT_HELENA("Saint Helena"),
    NAME_SLOVENIA("Slovenia"),
    NAME_SVALBARD_AND_JAN_MAYEN_ISLANDS("Svalbard And Jan Mayen Islands"),
    NAME_SLOVAK_REPUBLIC("Slovak Republic"),
    NAME_SIERRA_LEONE("Sierra Leone"),
    NAME_SAN_MARINO("San Marino"),
    NAME_SENEGAL("Senegal"),
    NAME_SOMALIA("Somalia"),
    NAME_SURINAME("Suriname"),
    NAME_SAINT_TOME_SAO_TOME_AND_PRINCIPE("Saint Tome (Sao Tome) And Principe"),
    NAME_FORMER_USSR("Former USSR"),
    NAME_EL_SALVADOR("El Salvador"),
    NAME_SYRIA("Syria"),
    NAME_SWAZILAND("Swaziland"),
    NAME_TURKS_AND_CAICOS_ISLANDS("Turks And Caicos Islands"),
    NAME_CHAD("Chad"),
    NAME_FRENCH_SOUTHERN_TERRITORIES("French Southern Territories"),
    NAME_TOGO("Togo"),
    NAME_THAILAND("Thailand"),
    NAME_TADJIKISTAN("Tadjikistan"),
    NAME_TOKELAU("Tokelau"),
    NAME_TURKMENISTAN("Turkmenistan"),
    NAME_TUNISIA("Tunisia"),
    NAME_TONGA("Tonga"),
    NAME_EAST_TIMOR("East Timor"),
    NAME_TURKEY("Turkey"),
    NAME_TRINIDAD_AND_TOBAGO("Trinidad And Tobago"),
    NAME_TUVALU("Tuvalu"),
    NAME_TAIWAN("Taiwan"),
    NAME_TANZANIA("Tanzania"),
    NAME_UKRAINE("Ukraine"),
    NAME_UGANDA("Uganda"),
    NAME_UNITED_KINGDOM("United Kingdom"),
    NAME_USA_MINOR_OUTLYING_ISLANDS("USA Minor Outlying Islands"),
    NAME_UNITED_STATES("United States"),
    NAME_URUGUAY("Uruguay"),
    NAME_UZBEKISTAN("Uzbekistan"),
    NAME_HOLY_SEE_VATICAN_CITY_STATE("Holy See (Vatican City State)"),
    NAME_SAINT_VINCENT_GRENADINES("Saint Vincent & Grenadines"),
    NAME_VENEZUELA("Venezuela"),
    NAME_VIRGIN_ISLANDS_BRITISH("Virgin Islands (British)"),
    NAME_VIRGIN_ISLANDS_USA("Virgin Islands (USA)"),
    NAME_VIETNAM("Vietnam"),
    NAME_VANUATU("Vanuatu"),
    NAME_WALLIS_AND_FUTUNA_ISLANDS("Wallis And Futuna Islands"),
    NAME_SAMOA("Samoa"),
    NAME_YEMEN("Yemen"),
    NAME_MAYOTTE("Mayotte"),
    NAME_YUGOSLAVIA("Yugoslavia"),
    NAME_SOUTH_AFRICA("South Africa"),
    NAME_ZAMBIA("Zambia"),
    NAME_ZAIRE("Zaire"),
    NAME_ZIMBABWE("Zimbabwe");

    private final String role;

    CountryNames(String role) {
        this.role = role;
    }
}
