package it.asansonne.storybe.constants;

import static it.cybsec.app.constants.CountryCodes.*;
import static it.cybsec.app.constants.CountryNames.*;

import java.util.HashMap;
import java.util.Map;

public class Country {
    private final Map<String, String> map;

    public Country() {
        map = new HashMap<>();
        map.put(NAME_ANDORRA_PRINCIPALITY_OF.getRole(), CODE_ANDORRA_PRINCIPALITY_OF.getRole());
        map.put(NAME_UNITED_ARAB_EMIRATES.getRole(), CODE_UNITED_ARAB_EMIRATES.getRole());
        map.put(NAME_AFGHANISTAN_ISLAMIC_STATE_OF.getRole(), CODE_AFGHANISTAN_ISLAMIC_STATE_OF.getRole());
        map.put(NAME_ANTIGUA_AND_BARBUDA.getRole(), CODE_ANTIGUA_AND_BARBUDA.getRole());
        map.put(NAME_ANGUILLA.getRole(), CODE_ANGUILLA.getRole());
        map.put(NAME_ALBANIA.getRole(), CODE_ALBANIA.getRole());
        map.put(NAME_ARMENIA.getRole(), CODE_ARMENIA.getRole());
        map.put(NAME_NETHERLANDS_ANTILLES.getRole(), CODE_NETHERLANDS_ANTILLES.getRole());
        map.put(NAME_ANGOLA.getRole(), CODE_ANGOLA.getRole());
        map.put(NAME_ANTARCTICA.getRole(), CODE_ANTARCTICA.getRole());
        map.put(NAME_ARGENTINA.getRole(), CODE_ARGENTINA.getRole());
        map.put(NAME_AMERICAN_SAMOA.getRole(), CODE_AMERICAN_SAMOA.getRole());
        map.put(NAME_AUSTRIA.getRole(), CODE_AUSTRIA.getRole());
        map.put(NAME_AUSTRALIA.getRole(), CODE_AUSTRALIA.getRole());
        map.put(NAME_ARUBA.getRole(), CODE_ARUBA.getRole());
        map.put(NAME_AZERBAIDJAN.getRole(), CODE_AZERBAIDJAN.getRole());
        map.put(NAME_BOSNIA_HERZEGOVINA.getRole(), CODE_BOSNIA_HERZEGOVINA.getRole());
        map.put(NAME_BARBADOS.getRole(), CODE_BARBADOS.getRole());
        map.put(NAME_BANGLADESH.getRole(), CODE_BANGLADESH.getRole());
        map.put(NAME_BELGIUM.getRole(), CODE_BELGIUM.getRole());
        map.put(NAME_BURKINA_FASO.getRole(), CODE_BURKINA_FASO.getRole());
        map.put(NAME_BULGARIA.getRole(), CODE_BULGARIA.getRole());
        map.put(NAME_BAHRAIN.getRole(), CODE_BAHRAIN.getRole());
        map.put(NAME_BURUNDI.getRole(), CODE_BURUNDI.getRole());
        map.put(NAME_BENIN.getRole(), CODE_BENIN.getRole());
        map.put(NAME_BERMUDA.getRole(), CODE_BERMUDA.getRole());
        map.put(NAME_BRUNEI_DARUSSALAM.getRole(), CODE_BRUNEI_DARUSSALAM.getRole());
        map.put(NAME_BOLIVIA.getRole(), CODE_BOLIVIA.getRole());
        map.put(NAME_BRAZIL.getRole(), CODE_BRAZIL.getRole());
        map.put(NAME_BAHAMAS.getRole(), CODE_BAHAMAS.getRole());
        map.put(NAME_BHUTAN.getRole(), CODE_BHUTAN.getRole());
        map.put(NAME_BOUVET_ISLAND.getRole(), CODE_BOUVET_ISLAND.getRole());
        map.put(NAME_BOTSWANA.getRole(), CODE_BOTSWANA.getRole());
        map.put(NAME_BELARUS.getRole(), CODE_BELARUS.getRole());
        map.put(NAME_BELIZE.getRole(), CODE_BELIZE.getRole());
        map.put(NAME_CANADA.getRole(), CODE_CANADA.getRole());
        map.put(NAME_COCOS_KEELING_ISLANDS.getRole(), CODE_COCOS_KEELING_ISLANDS.getRole());
        map.put(NAME_CENTRAL_AFRICAN_REPUBLIC.getRole(), CODE_CENTRAL_AFRICAN_REPUBLIC.getRole());
        map.put(NAME_CONGO_DEMOCRATIC_REPUBLIC_OF_THE.getRole(), CODE_CONGO_DEMOCRATIC_REPUBLIC_OF_THE.getRole());
        map.put(NAME_CONGO.getRole(), CODE_CONGO.getRole());
        map.put(NAME_SWITZERLAND.getRole(), CODE_SWITZERLAND.getRole());
        map.put(NAME_IVORY_COAST_COTE_D_IVOIRE.getRole(), CODE_IVORY_COAST_COTE_D_IVOIRE.getRole());
        map.put(NAME_COOK_ISLANDS.getRole(), CODE_COOK_ISLANDS.getRole());
        map.put(NAME_CHILE.getRole(), CODE_CHILE.getRole());
        map.put(NAME_CAMEROON.getRole(), CODE_CAMEROON.getRole());
        map.put(NAME_CHINA.getRole(), CODE_CHINA.getRole());
        map.put(NAME_COLOMBIA.getRole(), CODE_COLOMBIA.getRole());
        map.put(NAME_COSTA_RICA.getRole(), CODE_COSTA_RICA.getRole());
        map.put(NAME_FORMER_CZECHOSLOVAKIA.getRole(), CODE_FORMER_CZECHOSLOVAKIA.getRole());
        map.put(NAME_CUBA.getRole(), CODE_CUBA.getRole());
        map.put(NAME_CAPE_VERDE.getRole(), CODE_CAPE_VERDE.getRole());
        map.put(NAME_CHRISTMAS_ISLAND.getRole(), CODE_CHRISTMAS_ISLAND.getRole());
        map.put(NAME_CYPRUS.getRole(), CODE_CYPRUS.getRole());
        map.put(NAME_CZECH_REPUBLIC.getRole(), CODE_CZECH_REPUBLIC.getRole());
        map.put(NAME_GERMANY.getRole(), CODE_GERMANY.getRole());
        map.put(NAME_DJIBOUTI.getRole(), CODE_DJIBOUTI.getRole());
        map.put(NAME_DENMARK.getRole(), CODE_DENMARK.getRole());
        map.put(NAME_DOMINICA.getRole(), CODE_DOMINICA.getRole());
        map.put(NAME_DOMINICAN_REPUBLIC.getRole(), CODE_DOMINICAN_REPUBLIC.getRole());
        map.put(NAME_ALGERIA.getRole(), CODE_ALGERIA.getRole());
        map.put(NAME_ECUADOR.getRole(), CODE_ECUADOR.getRole());
        map.put(NAME_ESTONIA.getRole(), CODE_ESTONIA.getRole());
        map.put(NAME_EGYPT.getRole(), CODE_EGYPT.getRole());
        map.put(NAME_WESTERN_SAHARA.getRole(), CODE_WESTERN_SAHARA.getRole());
        map.put(NAME_ERITREA.getRole(), CODE_ERITREA.getRole());
        map.put(NAME_SPAIN.getRole(), CODE_SPAIN.getRole());
        map.put(NAME_ETHIOPIA.getRole(), CODE_ETHIOPIA.getRole());
        map.put(NAME_FINLAND.getRole(), CODE_FINLAND.getRole());
        map.put(NAME_FIJI.getRole(), CODE_FIJI.getRole());
        map.put(NAME_FALKLAND_ISLANDS.getRole(), CODE_FALKLAND_ISLANDS.getRole());
        map.put(NAME_MICRONESIA.getRole(), CODE_MICRONESIA.getRole());
        map.put(NAME_FAROE_ISLANDS.getRole(), CODE_FAROE_ISLANDS.getRole());
        map.put(NAME_FRANCE.getRole(), CODE_FRANCE.getRole());
        map.put(NAME_FRANCE_EUROPEAN_TERRITORY.getRole(), CODE_FRANCE_EUROPEAN_TERRITORY.getRole());
        map.put(NAME_GABON.getRole(), CODE_GABON.getRole());
        map.put(NAME_GREAT_BRITAIN.getRole(), CODE_GREAT_BRITAIN.getRole());
        map.put(NAME_GRENADA.getRole(), CODE_GRENADA.getRole());
        map.put(NAME_GEORGIA.getRole(), CODE_GEORGIA.getRole());
        map.put(NAME_GHANA.getRole(), CODE_GHANA.getRole());
        map.put(NAME_GIBRALTAR.getRole(), CODE_GIBRALTAR.getRole());
        map.put(NAME_GREENLAND.getRole(), CODE_GREENLAND.getRole());
        map.put(NAME_GAMBIA.getRole(), CODE_GAMBIA.getRole());
        map.put(NAME_GUINEA.getRole(), CODE_GUINEA.getRole());
        map.put(NAME_EQUATORIAL_GUINEA.getRole(), CODE_EQUATORIAL_GUINEA.getRole());
        map.put(NAME_GREECE.getRole(), CODE_GREECE.getRole());
        map.put(NAME_GUATEMALA.getRole(), CODE_GUATEMALA.getRole());
        map.put(NAME_GUINEA_BISSAU.getRole(), CODE_GUINEA_BISSAU.getRole());
        map.put(NAME_GUYANA.getRole(), CODE_GUYANA.getRole());
        map.put(NAME_HONG_KONG.getRole(), CODE_HONG_KONG.getRole());
        map.put(NAME_HONDURAS.getRole(), CODE_HONDURAS.getRole());
        map.put(NAME_CROATIA.getRole(), CODE_CROATIA.getRole());
        map.put(NAME_HAITI.getRole(), CODE_HAITI.getRole());
        map.put(NAME_HUNGARY.getRole(), CODE_HUNGARY.getRole());
        map.put(NAME_INDONESIA.getRole(), CODE_INDONESIA.getRole());
        map.put(NAME_INDIA.getRole(), CODE_INDIA.getRole());
        map.put(NAME_BRITISH_INDIAN_OCEAN_TERRITORY.getRole(), CODE_BRITISH_INDIAN_OCEAN_TERRITORY.getRole());
        map.put(NAME_IRELAND.getRole(), CODE_IRELAND.getRole());
        map.put(NAME_IRAQ.getRole(), CODE_IRAQ.getRole());
        map.put(NAME_ICELAND.getRole(), CODE_ICELAND.getRole());
        map.put(NAME_ISRAEL.getRole(), CODE_ISRAEL.getRole());
        map.put(NAME_ITALY.getRole(), CODE_ITALY.getRole());
        map.put(NAME_JAMAICA.getRole(), CODE_JAMAICA.getRole());
        map.put(NAME_JORDAN.getRole(), CODE_JORDAN.getRole());
        map.put(NAME_JAPAN.getRole(), CODE_JAPAN.getRole());
        map.put(NAME_KENYA.getRole(), CODE_KENYA.getRole());
        map.put(NAME_KIRIBATI.getRole(), CODE_KIRIBATI.getRole());
        map.put(NAME_COMOROS.getRole(), CODE_COMOROS.getRole());
        map.put(NAME_NORTH_KOREA.getRole(), CODE_NORTH_KOREA.getRole());
        map.put(NAME_SOUTH_KOREA.getRole(), CODE_SOUTH_KOREA.getRole());
        map.put(NAME_KUWAIT.getRole(), CODE_KUWAIT.getRole());
        map.put(NAME_CAYMAN_ISLANDS.getRole(), CODE_CAYMAN_ISLANDS.getRole());
        map.put(NAME_KAZAKHSTAN.getRole(), CODE_KAZAKHSTAN.getRole());
        map.put(NAME_LEBANON.getRole(), CODE_LEBANON.getRole());
        map.put(NAME_SAINT_LUCIA.getRole(), CODE_SAINT_LUCIA.getRole());
        map.put(NAME_LIECHTENSTEIN.getRole(), CODE_LIECHTENSTEIN.getRole());
        map.put(NAME_SRI_LANKA.getRole(), CODE_SRI_LANKA.getRole());
        map.put(NAME_LIBERIA.getRole(), CODE_LIBERIA.getRole());
        map.put(NAME_LESOTHO.getRole(), CODE_LESOTHO.getRole());
        map.put(NAME_LITHUANIA.getRole(), CODE_LITHUANIA.getRole());
        map.put(NAME_LUXEMBOURG.getRole(), CODE_LUXEMBOURG.getRole());
        map.put(NAME_LATVIA.getRole(), CODE_LATVIA.getRole());
        map.put(NAME_MOROCCO.getRole(), CODE_MOROCCO.getRole());
        map.put(NAME_MONACO.getRole(), CODE_MONACO.getRole());
        map.put(NAME_MADAGASCAR.getRole(), CODE_MADAGASCAR.getRole());
        map.put(NAME_MARSHALL_ISLANDS.getRole(), CODE_MARSHALL_ISLANDS.getRole());
        map.put(NAME_MALI.getRole(), CODE_MALI.getRole());
        map.put(NAME_MYANMAR.getRole(), CODE_MYANMAR.getRole());
        map.put(NAME_MONGOLIA.getRole(), CODE_MONGOLIA.getRole());
        map.put(NAME_MACAU.getRole(), CODE_MACAU.getRole());
        map.put(NAME_NORTHERN_MARIANA_ISLANDS.getRole(), CODE_NORTHERN_MARIANA_ISLANDS.getRole());
        map.put(NAME_MAURITANIA.getRole(), CODE_MAURITANIA.getRole());
        map.put(NAME_MONTSERRAT.getRole(), CODE_MONTSERRAT.getRole());
        map.put(NAME_MALTA.getRole(), CODE_MALTA.getRole());
        map.put(NAME_MAURITIUS.getRole(), CODE_MAURITIUS.getRole());
        map.put(NAME_MALDIVES.getRole(), CODE_MALDIVES.getRole());
        map.put(NAME_MALAWI.getRole(), CODE_MALAWI.getRole());
        map.put(NAME_MEXICO.getRole(), CODE_MEXICO.getRole());
        map.put(NAME_MALAYSIA.getRole(), CODE_MALAYSIA.getRole());
        map.put(NAME_MOZAMBIQUE.getRole(), CODE_MOZAMBIQUE.getRole());
        map.put(NAME_NAMIBIA.getRole(), CODE_NAMIBIA.getRole());
        map.put(NAME_NIGER.getRole(), CODE_NIGER.getRole());
        map.put(NAME_NORFOLK_ISLAND.getRole(), CODE_NORFOLK_ISLAND.getRole());
        map.put(NAME_NIGERIA.getRole(), CODE_NIGERIA.getRole());
        map.put(NAME_NICARAGUA.getRole(), CODE_NICARAGUA.getRole());
        map.put(NAME_NETHERLANDS.getRole(), CODE_NETHERLANDS.getRole());
        map.put(NAME_NORWAY.getRole(), CODE_NORWAY.getRole());
        map.put(NAME_NEPAL.getRole(), CODE_NEPAL.getRole());
        map.put(NAME_NAURU.getRole(), CODE_NAURU.getRole());
        map.put(NAME_NIUE.getRole(), CODE_NIUE.getRole());
        map.put(NAME_NEW_ZEALAND.getRole(), CODE_NEW_ZEALAND.getRole());
        map.put(NAME_OMAN.getRole(), CODE_OMAN.getRole());
        map.put(NAME_PANAMA.getRole(), CODE_PANAMA.getRole());
        map.put(NAME_PERU.getRole(), CODE_PERU.getRole());
        map.put(NAME_PAPUA_NEW_GUINEA.getRole(), CODE_PAPUA_NEW_GUINEA.getRole());
        map.put(NAME_PHILIPPINES.getRole(), CODE_PHILIPPINES.getRole());
        map.put(NAME_PAKISTAN.getRole(), CODE_PAKISTAN.getRole());
        map.put(NAME_POLAND.getRole(), CODE_POLAND.getRole());
        map.put(NAME_PITCAIRN_ISLAND.getRole(), CODE_PITCAIRN_ISLAND.getRole());
        map.put(NAME_PUERTO_RICO.getRole(), CODE_PUERTO_RICO.getRole());
        map.put(NAME_PORTUGAL.getRole(), CODE_PORTUGAL.getRole());
        map.put(NAME_PALAU.getRole(), CODE_PALAU.getRole());
        map.put(NAME_PARAGUAY.getRole(), CODE_PARAGUAY.getRole());
        map.put(NAME_QATAR.getRole(), CODE_QATAR.getRole());
        map.put(NAME_ROMANIA.getRole(), CODE_ROMANIA.getRole());
        map.put(NAME_RUSSIAN_FEDERATION.getRole(), CODE_RUSSIAN_FEDERATION.getRole());
        map.put(NAME_RWANDA.getRole(), CODE_RWANDA.getRole());
        map.put(NAME_SAUDI_ARABIA.getRole(), CODE_SAUDI_ARABIA.getRole());
        map.put(NAME_SOLOMON_ISLANDS.getRole(), CODE_SOLOMON_ISLANDS.getRole());
        map.put(NAME_SEYCHELLES.getRole(), CODE_SEYCHELLES.getRole());
        map.put(NAME_SUDAN.getRole(), CODE_SUDAN.getRole());
        map.put(NAME_SWEDEN.getRole(), CODE_SWEDEN.getRole());
        map.put(NAME_SINGAPORE.getRole(), CODE_SINGAPORE.getRole());
        map.put(NAME_SAINT_HELENA.getRole(), CODE_SAINT_HELENA.getRole());
        map.put(NAME_SLOVENIA.getRole(), CODE_SLOVENIA.getRole());
        map.put(NAME_SVALBARD_AND_JAN_MAYEN_ISLANDS.getRole(), CODE_SVALBARD_AND_JAN_MAYEN_ISLANDS.getRole());
        map.put(NAME_SLOVAK_REPUBLIC.getRole(), CODE_SLOVAK_REPUBLIC.getRole());
        map.put(NAME_SIERRA_LEONE.getRole(), CODE_SIERRA_LEONE.getRole());
        map.put(NAME_SAN_MARINO.getRole(), CODE_SAN_MARINO.getRole());
        map.put(NAME_SENEGAL.getRole(), CODE_SENEGAL.getRole());
        map.put(NAME_SOMALIA.getRole(), CODE_SOMALIA.getRole());
        map.put(NAME_SURINAME.getRole(), CODE_SURINAME.getRole());
        map.put(NAME_EL_SALVADOR.getRole(), CODE_EL_SALVADOR.getRole());
        map.put(NAME_SWAZILAND.getRole(), CODE_SWAZILAND.getRole());
        map.put(NAME_TURKS_AND_CAICOS_ISLANDS.getRole(), CODE_TURKS_AND_CAICOS_ISLANDS.getRole());
        map.put(NAME_CHAD.getRole(), CODE_CHAD.getRole());
        map.put(NAME_FRENCH_SOUTHERN_TERRITORIES.getRole(), CODE_FRENCH_SOUTHERN_TERRITORIES.getRole());
        map.put(NAME_TOGO.getRole(), CODE_TOGO.getRole());
        map.put(NAME_THAILAND.getRole(), CODE_THAILAND.getRole());
        map.put(NAME_TOKELAU.getRole(), CODE_TOKELAU.getRole());
        map.put(NAME_TURKMENISTAN.getRole(), CODE_TURKMENISTAN.getRole());
        map.put(NAME_TUNISIA.getRole(), CODE_TUNISIA.getRole());
        map.put(NAME_TONGA.getRole(), CODE_TONGA.getRole());
        map.put(NAME_EAST_TIMOR.getRole(), CODE_EAST_TIMOR.getRole());
        map.put(NAME_TURKEY.getRole(), CODE_TURKEY.getRole());
        map.put(NAME_TRINIDAD_AND_TOBAGO.getRole(), CODE_TRINIDAD_AND_TOBAGO.getRole());
        map.put(NAME_TUVALU.getRole(), CODE_TUVALU.getRole());
        map.put(NAME_UKRAINE.getRole(), CODE_UKRAINE.getRole());
        map.put(NAME_UGANDA.getRole(), CODE_UGANDA.getRole());
        map.put(NAME_UNITED_KINGDOM.getRole(), CODE_UNITED_KINGDOM.getRole());
        map.put(NAME_UNITED_STATES.getRole(), CODE_UNITED_STATES.getRole());
        map.put(NAME_URUGUAY.getRole(), CODE_URUGUAY.getRole());
        map.put(NAME_UZBEKISTAN.getRole(), CODE_UZBEKISTAN.getRole());
        map.put(NAME_VENEZUELA.getRole(), CODE_VENEZUELA.getRole());
        map.put(NAME_VIRGIN_ISLANDS_BRITISH.getRole(), CODE_VIRGIN_ISLANDS_BRITISH.getRole());
        map.put(NAME_VANUATU.getRole(), CODE_VANUATU.getRole());
        map.put(NAME_WALLIS_AND_FUTUNA_ISLANDS.getRole(), CODE_WALLIS_AND_FUTUNA_ISLANDS.getRole());
        map.put(NAME_WESTERN_SAHARA.getRole(), CODE_WESTERN_SAHARA.getRole());
        map.put(NAME_YEMEN.getRole(), CODE_YEMEN.getRole());
        map.put(NAME_MAYOTTE.getRole(), CODE_MAYOTTE.getRole());
        map.put(NAME_YUGOSLAVIA.getRole(), CODE_YUGOSLAVIA.getRole());
        map.put(NAME_SOUTH_AFRICA.getRole(), CODE_SOUTH_AFRICA.getRole());
        map.put(NAME_ZAMBIA.getRole(), CODE_ZAMBIA.getRole());
        map.put(NAME_ZIMBABWE.getRole(), CODE_ZIMBABWE.getRole());
    }

    public String getName(String country) {
        String countryFound = map.get(country);
        if (countryFound == null) {
            countryFound = "Italy";
        }
        return countryFound;
    }

    public String getCode(String country) {
        String countryFound = map.get(country);
        if (countryFound == null) {
            countryFound = "IT";
        }
        return countryFound;
    }

}


