package it.asansonne.storybe.constants;

import static it.asansonne.storybe.constants.CountryCodes.CODE_AFGHANISTAN_ISLAMIC_STATE_OF;
import static it.asansonne.storybe.constants.CountryCodes.CODE_ALBANIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_ALGERIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_AMERICAN_SAMOA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_ANDORRA_PRINCIPALITY_OF;
import static it.asansonne.storybe.constants.CountryCodes.CODE_ANGOLA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_ANGUILLA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_ANTARCTICA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_ANTIGUA_AND_BARBUDA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_ARGENTINA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_ARMENIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_ARUBA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_AUSTRALIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_AUSTRIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_AZERBAIDJAN;
import static it.asansonne.storybe.constants.CountryCodes.CODE_BAHAMAS;
import static it.asansonne.storybe.constants.CountryCodes.CODE_BAHRAIN;
import static it.asansonne.storybe.constants.CountryCodes.CODE_BANGLADESH;
import static it.asansonne.storybe.constants.CountryCodes.CODE_BARBADOS;
import static it.asansonne.storybe.constants.CountryCodes.CODE_BELARUS;
import static it.asansonne.storybe.constants.CountryCodes.CODE_BELGIUM;
import static it.asansonne.storybe.constants.CountryCodes.CODE_BELIZE;
import static it.asansonne.storybe.constants.CountryCodes.CODE_BENIN;
import static it.asansonne.storybe.constants.CountryCodes.CODE_BERMUDA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_BHUTAN;
import static it.asansonne.storybe.constants.CountryCodes.CODE_BOLIVIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_BOSNIA_HERZEGOVINA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_BOTSWANA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_BOUVET_ISLAND;
import static it.asansonne.storybe.constants.CountryCodes.CODE_BRAZIL;
import static it.asansonne.storybe.constants.CountryCodes.CODE_BRITISH_INDIAN_OCEAN_TERRITORY;
import static it.asansonne.storybe.constants.CountryCodes.CODE_BRUNEI_DARUSSALAM;
import static it.asansonne.storybe.constants.CountryCodes.CODE_BULGARIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_BURKINA_FASO;
import static it.asansonne.storybe.constants.CountryCodes.CODE_BURUNDI;
import static it.asansonne.storybe.constants.CountryCodes.CODE_CAMEROON;
import static it.asansonne.storybe.constants.CountryCodes.CODE_CANADA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_CAPE_VERDE;
import static it.asansonne.storybe.constants.CountryCodes.CODE_CAYMAN_ISLANDS;
import static it.asansonne.storybe.constants.CountryCodes.CODE_CENTRAL_AFRICAN_REPUBLIC;
import static it.asansonne.storybe.constants.CountryCodes.CODE_CHAD;
import static it.asansonne.storybe.constants.CountryCodes.CODE_CHILE;
import static it.asansonne.storybe.constants.CountryCodes.CODE_CHINA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_CHRISTMAS_ISLAND;
import static it.asansonne.storybe.constants.CountryCodes.CODE_COCOS_KEELING_ISLANDS;
import static it.asansonne.storybe.constants.CountryCodes.CODE_COLOMBIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_COMOROS;
import static it.asansonne.storybe.constants.CountryCodes.CODE_CONGO;
import static it.asansonne.storybe.constants.CountryCodes.CODE_CONGO_DEMOCRATIC_REPUBLIC_OF_THE;
import static it.asansonne.storybe.constants.CountryCodes.CODE_COOK_ISLANDS;
import static it.asansonne.storybe.constants.CountryCodes.CODE_COSTA_RICA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_CROATIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_CUBA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_CYPRUS;
import static it.asansonne.storybe.constants.CountryCodes.CODE_CZECH_REPUBLIC;
import static it.asansonne.storybe.constants.CountryCodes.CODE_DENMARK;
import static it.asansonne.storybe.constants.CountryCodes.CODE_DJIBOUTI;
import static it.asansonne.storybe.constants.CountryCodes.CODE_DOMINICA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_DOMINICAN_REPUBLIC;
import static it.asansonne.storybe.constants.CountryCodes.CODE_EAST_TIMOR;
import static it.asansonne.storybe.constants.CountryCodes.CODE_ECUADOR;
import static it.asansonne.storybe.constants.CountryCodes.CODE_EGYPT;
import static it.asansonne.storybe.constants.CountryCodes.CODE_EL_SALVADOR;
import static it.asansonne.storybe.constants.CountryCodes.CODE_EQUATORIAL_GUINEA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_ERITREA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_ESTONIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_ETHIOPIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_FALKLAND_ISLANDS;
import static it.asansonne.storybe.constants.CountryCodes.CODE_FAROE_ISLANDS;
import static it.asansonne.storybe.constants.CountryCodes.CODE_FIJI;
import static it.asansonne.storybe.constants.CountryCodes.CODE_FINLAND;
import static it.asansonne.storybe.constants.CountryCodes.CODE_FORMER_CZECHOSLOVAKIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_FRANCE;
import static it.asansonne.storybe.constants.CountryCodes.CODE_FRANCE_EUROPEAN_TERRITORY;
import static it.asansonne.storybe.constants.CountryCodes.CODE_FRENCH_SOUTHERN_TERRITORIES;
import static it.asansonne.storybe.constants.CountryCodes.CODE_GABON;
import static it.asansonne.storybe.constants.CountryCodes.CODE_GAMBIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_GEORGIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_GERMANY;
import static it.asansonne.storybe.constants.CountryCodes.CODE_GHANA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_GIBRALTAR;
import static it.asansonne.storybe.constants.CountryCodes.CODE_GREAT_BRITAIN;
import static it.asansonne.storybe.constants.CountryCodes.CODE_GREECE;
import static it.asansonne.storybe.constants.CountryCodes.CODE_GREENLAND;
import static it.asansonne.storybe.constants.CountryCodes.CODE_GRENADA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_GUATEMALA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_GUINEA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_GUINEA_BISSAU;
import static it.asansonne.storybe.constants.CountryCodes.CODE_GUYANA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_HAITI;
import static it.asansonne.storybe.constants.CountryCodes.CODE_HONDURAS;
import static it.asansonne.storybe.constants.CountryCodes.CODE_HONG_KONG;
import static it.asansonne.storybe.constants.CountryCodes.CODE_HUNGARY;
import static it.asansonne.storybe.constants.CountryCodes.CODE_ICELAND;
import static it.asansonne.storybe.constants.CountryCodes.CODE_INDIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_INDONESIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_IRAQ;
import static it.asansonne.storybe.constants.CountryCodes.CODE_IRELAND;
import static it.asansonne.storybe.constants.CountryCodes.CODE_ISRAEL;
import static it.asansonne.storybe.constants.CountryCodes.CODE_ITALY;
import static it.asansonne.storybe.constants.CountryCodes.CODE_IVORY_COAST_COTE_D_IVOIRE;
import static it.asansonne.storybe.constants.CountryCodes.CODE_JAMAICA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_JAPAN;
import static it.asansonne.storybe.constants.CountryCodes.CODE_JORDAN;
import static it.asansonne.storybe.constants.CountryCodes.CODE_KAZAKHSTAN;
import static it.asansonne.storybe.constants.CountryCodes.CODE_KENYA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_KIRIBATI;
import static it.asansonne.storybe.constants.CountryCodes.CODE_KUWAIT;
import static it.asansonne.storybe.constants.CountryCodes.CODE_LATVIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_LEBANON;
import static it.asansonne.storybe.constants.CountryCodes.CODE_LESOTHO;
import static it.asansonne.storybe.constants.CountryCodes.CODE_LIBERIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_LIECHTENSTEIN;
import static it.asansonne.storybe.constants.CountryCodes.CODE_LITHUANIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_LUXEMBOURG;
import static it.asansonne.storybe.constants.CountryCodes.CODE_MACAU;
import static it.asansonne.storybe.constants.CountryCodes.CODE_MADAGASCAR;
import static it.asansonne.storybe.constants.CountryCodes.CODE_MALAWI;
import static it.asansonne.storybe.constants.CountryCodes.CODE_MALAYSIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_MALDIVES;
import static it.asansonne.storybe.constants.CountryCodes.CODE_MALI;
import static it.asansonne.storybe.constants.CountryCodes.CODE_MALTA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_MARSHALL_ISLANDS;
import static it.asansonne.storybe.constants.CountryCodes.CODE_MAURITANIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_MAURITIUS;
import static it.asansonne.storybe.constants.CountryCodes.CODE_MAYOTTE;
import static it.asansonne.storybe.constants.CountryCodes.CODE_MEXICO;
import static it.asansonne.storybe.constants.CountryCodes.CODE_MICRONESIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_MONACO;
import static it.asansonne.storybe.constants.CountryCodes.CODE_MONGOLIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_MONTSERRAT;
import static it.asansonne.storybe.constants.CountryCodes.CODE_MOROCCO;
import static it.asansonne.storybe.constants.CountryCodes.CODE_MOZAMBIQUE;
import static it.asansonne.storybe.constants.CountryCodes.CODE_MYANMAR;
import static it.asansonne.storybe.constants.CountryCodes.CODE_NAMIBIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_NAURU;
import static it.asansonne.storybe.constants.CountryCodes.CODE_NEPAL;
import static it.asansonne.storybe.constants.CountryCodes.CODE_NETHERLANDS;
import static it.asansonne.storybe.constants.CountryCodes.CODE_NETHERLANDS_ANTILLES;
import static it.asansonne.storybe.constants.CountryCodes.CODE_NEW_ZEALAND;
import static it.asansonne.storybe.constants.CountryCodes.CODE_NICARAGUA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_NIGER;
import static it.asansonne.storybe.constants.CountryCodes.CODE_NIGERIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_NIUE;
import static it.asansonne.storybe.constants.CountryCodes.CODE_NORFOLK_ISLAND;
import static it.asansonne.storybe.constants.CountryCodes.CODE_NORTHERN_MARIANA_ISLANDS;
import static it.asansonne.storybe.constants.CountryCodes.CODE_NORTH_KOREA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_NORWAY;
import static it.asansonne.storybe.constants.CountryCodes.CODE_OMAN;
import static it.asansonne.storybe.constants.CountryCodes.CODE_PAKISTAN;
import static it.asansonne.storybe.constants.CountryCodes.CODE_PALAU;
import static it.asansonne.storybe.constants.CountryCodes.CODE_PANAMA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_PAPUA_NEW_GUINEA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_PARAGUAY;
import static it.asansonne.storybe.constants.CountryCodes.CODE_PERU;
import static it.asansonne.storybe.constants.CountryCodes.CODE_PHILIPPINES;
import static it.asansonne.storybe.constants.CountryCodes.CODE_PITCAIRN_ISLAND;
import static it.asansonne.storybe.constants.CountryCodes.CODE_POLAND;
import static it.asansonne.storybe.constants.CountryCodes.CODE_PORTUGAL;
import static it.asansonne.storybe.constants.CountryCodes.CODE_PUERTO_RICO;
import static it.asansonne.storybe.constants.CountryCodes.CODE_QATAR;
import static it.asansonne.storybe.constants.CountryCodes.CODE_ROMANIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_RUSSIAN_FEDERATION;
import static it.asansonne.storybe.constants.CountryCodes.CODE_RWANDA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SAINT_HELENA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SAINT_LUCIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SAN_MARINO;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SAUDI_ARABIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SENEGAL;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SEYCHELLES;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SIERRA_LEONE;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SINGAPORE;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SLOVAK_REPUBLIC;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SLOVENIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SOLOMON_ISLANDS;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SOMALIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SOUTH_AFRICA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SOUTH_KOREA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SPAIN;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SRI_LANKA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SUDAN;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SURINAME;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SVALBARD_AND_JAN_MAYEN_ISLANDS;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SWAZILAND;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SWEDEN;
import static it.asansonne.storybe.constants.CountryCodes.CODE_SWITZERLAND;
import static it.asansonne.storybe.constants.CountryCodes.CODE_THAILAND;
import static it.asansonne.storybe.constants.CountryCodes.CODE_TOGO;
import static it.asansonne.storybe.constants.CountryCodes.CODE_TOKELAU;
import static it.asansonne.storybe.constants.CountryCodes.CODE_TONGA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_TRINIDAD_AND_TOBAGO;
import static it.asansonne.storybe.constants.CountryCodes.CODE_TUNISIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_TURKEY;
import static it.asansonne.storybe.constants.CountryCodes.CODE_TURKMENISTAN;
import static it.asansonne.storybe.constants.CountryCodes.CODE_TURKS_AND_CAICOS_ISLANDS;
import static it.asansonne.storybe.constants.CountryCodes.CODE_TUVALU;
import static it.asansonne.storybe.constants.CountryCodes.CODE_UGANDA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_UKRAINE;
import static it.asansonne.storybe.constants.CountryCodes.CODE_UNITED_ARAB_EMIRATES;
import static it.asansonne.storybe.constants.CountryCodes.CODE_UNITED_KINGDOM;
import static it.asansonne.storybe.constants.CountryCodes.CODE_UNITED_STATES;
import static it.asansonne.storybe.constants.CountryCodes.CODE_URUGUAY;
import static it.asansonne.storybe.constants.CountryCodes.CODE_UZBEKISTAN;
import static it.asansonne.storybe.constants.CountryCodes.CODE_VANUATU;
import static it.asansonne.storybe.constants.CountryCodes.CODE_VENEZUELA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_VIRGIN_ISLANDS_BRITISH;
import static it.asansonne.storybe.constants.CountryCodes.CODE_WALLIS_AND_FUTUNA_ISLANDS;
import static it.asansonne.storybe.constants.CountryCodes.CODE_WESTERN_SAHARA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_YEMEN;
import static it.asansonne.storybe.constants.CountryCodes.CODE_YUGOSLAVIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_ZAMBIA;
import static it.asansonne.storybe.constants.CountryCodes.CODE_ZIMBABWE;
import static it.asansonne.storybe.constants.CountryNames.NAME_AFGHANISTAN_ISLAMIC_STATE_OF;
import static it.asansonne.storybe.constants.CountryNames.NAME_ALBANIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_ALGERIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_AMERICAN_SAMOA;
import static it.asansonne.storybe.constants.CountryNames.NAME_ANDORRA_PRINCIPALITY_OF;
import static it.asansonne.storybe.constants.CountryNames.NAME_ANGOLA;
import static it.asansonne.storybe.constants.CountryNames.NAME_ANGUILLA;
import static it.asansonne.storybe.constants.CountryNames.NAME_ANTARCTICA;
import static it.asansonne.storybe.constants.CountryNames.NAME_ANTIGUA_AND_BARBUDA;
import static it.asansonne.storybe.constants.CountryNames.NAME_ARGENTINA;
import static it.asansonne.storybe.constants.CountryNames.NAME_ARMENIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_ARUBA;
import static it.asansonne.storybe.constants.CountryNames.NAME_AUSTRALIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_AUSTRIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_AZERBAIDJAN;
import static it.asansonne.storybe.constants.CountryNames.NAME_BAHAMAS;
import static it.asansonne.storybe.constants.CountryNames.NAME_BAHRAIN;
import static it.asansonne.storybe.constants.CountryNames.NAME_BANGLADESH;
import static it.asansonne.storybe.constants.CountryNames.NAME_BARBADOS;
import static it.asansonne.storybe.constants.CountryNames.NAME_BELARUS;
import static it.asansonne.storybe.constants.CountryNames.NAME_BELGIUM;
import static it.asansonne.storybe.constants.CountryNames.NAME_BELIZE;
import static it.asansonne.storybe.constants.CountryNames.NAME_BENIN;
import static it.asansonne.storybe.constants.CountryNames.NAME_BERMUDA;
import static it.asansonne.storybe.constants.CountryNames.NAME_BHUTAN;
import static it.asansonne.storybe.constants.CountryNames.NAME_BOLIVIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_BOSNIA_HERZEGOVINA;
import static it.asansonne.storybe.constants.CountryNames.NAME_BOTSWANA;
import static it.asansonne.storybe.constants.CountryNames.NAME_BOUVET_ISLAND;
import static it.asansonne.storybe.constants.CountryNames.NAME_BRAZIL;
import static it.asansonne.storybe.constants.CountryNames.NAME_BRITISH_INDIAN_OCEAN_TERRITORY;
import static it.asansonne.storybe.constants.CountryNames.NAME_BRUNEI_DARUSSALAM;
import static it.asansonne.storybe.constants.CountryNames.NAME_BULGARIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_BURKINA_FASO;
import static it.asansonne.storybe.constants.CountryNames.NAME_BURUNDI;
import static it.asansonne.storybe.constants.CountryNames.NAME_CAMEROON;
import static it.asansonne.storybe.constants.CountryNames.NAME_CANADA;
import static it.asansonne.storybe.constants.CountryNames.NAME_CAPE_VERDE;
import static it.asansonne.storybe.constants.CountryNames.NAME_CAYMAN_ISLANDS;
import static it.asansonne.storybe.constants.CountryNames.NAME_CENTRAL_AFRICAN_REPUBLIC;
import static it.asansonne.storybe.constants.CountryNames.NAME_CHAD;
import static it.asansonne.storybe.constants.CountryNames.NAME_CHILE;
import static it.asansonne.storybe.constants.CountryNames.NAME_CHINA;
import static it.asansonne.storybe.constants.CountryNames.NAME_CHRISTMAS_ISLAND;
import static it.asansonne.storybe.constants.CountryNames.NAME_COCOS_KEELING_ISLANDS;
import static it.asansonne.storybe.constants.CountryNames.NAME_COLOMBIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_COMOROS;
import static it.asansonne.storybe.constants.CountryNames.NAME_CONGO;
import static it.asansonne.storybe.constants.CountryNames.NAME_CONGO_DEMOCRATIC_REPUBLIC_OF_THE;
import static it.asansonne.storybe.constants.CountryNames.NAME_COOK_ISLANDS;
import static it.asansonne.storybe.constants.CountryNames.NAME_COSTA_RICA;
import static it.asansonne.storybe.constants.CountryNames.NAME_CROATIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_CUBA;
import static it.asansonne.storybe.constants.CountryNames.NAME_CYPRUS;
import static it.asansonne.storybe.constants.CountryNames.NAME_CZECH_REPUBLIC;
import static it.asansonne.storybe.constants.CountryNames.NAME_DENMARK;
import static it.asansonne.storybe.constants.CountryNames.NAME_DJIBOUTI;
import static it.asansonne.storybe.constants.CountryNames.NAME_DOMINICA;
import static it.asansonne.storybe.constants.CountryNames.NAME_DOMINICAN_REPUBLIC;
import static it.asansonne.storybe.constants.CountryNames.NAME_EAST_TIMOR;
import static it.asansonne.storybe.constants.CountryNames.NAME_ECUADOR;
import static it.asansonne.storybe.constants.CountryNames.NAME_EGYPT;
import static it.asansonne.storybe.constants.CountryNames.NAME_EL_SALVADOR;
import static it.asansonne.storybe.constants.CountryNames.NAME_EQUATORIAL_GUINEA;
import static it.asansonne.storybe.constants.CountryNames.NAME_ERITREA;
import static it.asansonne.storybe.constants.CountryNames.NAME_ESTONIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_ETHIOPIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_FALKLAND_ISLANDS;
import static it.asansonne.storybe.constants.CountryNames.NAME_FAROE_ISLANDS;
import static it.asansonne.storybe.constants.CountryNames.NAME_FIJI;
import static it.asansonne.storybe.constants.CountryNames.NAME_FINLAND;
import static it.asansonne.storybe.constants.CountryNames.NAME_FORMER_CZECHOSLOVAKIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_FRANCE;
import static it.asansonne.storybe.constants.CountryNames.NAME_FRANCE_EUROPEAN_TERRITORY;
import static it.asansonne.storybe.constants.CountryNames.NAME_FRENCH_SOUTHERN_TERRITORIES;
import static it.asansonne.storybe.constants.CountryNames.NAME_GABON;
import static it.asansonne.storybe.constants.CountryNames.NAME_GAMBIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_GEORGIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_GERMANY;
import static it.asansonne.storybe.constants.CountryNames.NAME_GHANA;
import static it.asansonne.storybe.constants.CountryNames.NAME_GIBRALTAR;
import static it.asansonne.storybe.constants.CountryNames.NAME_GREAT_BRITAIN;
import static it.asansonne.storybe.constants.CountryNames.NAME_GREECE;
import static it.asansonne.storybe.constants.CountryNames.NAME_GREENLAND;
import static it.asansonne.storybe.constants.CountryNames.NAME_GRENADA;
import static it.asansonne.storybe.constants.CountryNames.NAME_GUATEMALA;
import static it.asansonne.storybe.constants.CountryNames.NAME_GUINEA;
import static it.asansonne.storybe.constants.CountryNames.NAME_GUINEA_BISSAU;
import static it.asansonne.storybe.constants.CountryNames.NAME_GUYANA;
import static it.asansonne.storybe.constants.CountryNames.NAME_HAITI;
import static it.asansonne.storybe.constants.CountryNames.NAME_HONDURAS;
import static it.asansonne.storybe.constants.CountryNames.NAME_HONG_KONG;
import static it.asansonne.storybe.constants.CountryNames.NAME_HUNGARY;
import static it.asansonne.storybe.constants.CountryNames.NAME_ICELAND;
import static it.asansonne.storybe.constants.CountryNames.NAME_INDIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_INDONESIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_IRAQ;
import static it.asansonne.storybe.constants.CountryNames.NAME_IRELAND;
import static it.asansonne.storybe.constants.CountryNames.NAME_ISRAEL;
import static it.asansonne.storybe.constants.CountryNames.NAME_ITALY;
import static it.asansonne.storybe.constants.CountryNames.NAME_IVORY_COAST_COTE_D_IVOIRE;
import static it.asansonne.storybe.constants.CountryNames.NAME_JAMAICA;
import static it.asansonne.storybe.constants.CountryNames.NAME_JAPAN;
import static it.asansonne.storybe.constants.CountryNames.NAME_JORDAN;
import static it.asansonne.storybe.constants.CountryNames.NAME_KAZAKHSTAN;
import static it.asansonne.storybe.constants.CountryNames.NAME_KENYA;
import static it.asansonne.storybe.constants.CountryNames.NAME_KIRIBATI;
import static it.asansonne.storybe.constants.CountryNames.NAME_KUWAIT;
import static it.asansonne.storybe.constants.CountryNames.NAME_LATVIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_LEBANON;
import static it.asansonne.storybe.constants.CountryNames.NAME_LESOTHO;
import static it.asansonne.storybe.constants.CountryNames.NAME_LIBERIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_LIECHTENSTEIN;
import static it.asansonne.storybe.constants.CountryNames.NAME_LITHUANIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_LUXEMBOURG;
import static it.asansonne.storybe.constants.CountryNames.NAME_MACAU;
import static it.asansonne.storybe.constants.CountryNames.NAME_MADAGASCAR;
import static it.asansonne.storybe.constants.CountryNames.NAME_MALAWI;
import static it.asansonne.storybe.constants.CountryNames.NAME_MALAYSIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_MALDIVES;
import static it.asansonne.storybe.constants.CountryNames.NAME_MALI;
import static it.asansonne.storybe.constants.CountryNames.NAME_MALTA;
import static it.asansonne.storybe.constants.CountryNames.NAME_MARSHALL_ISLANDS;
import static it.asansonne.storybe.constants.CountryNames.NAME_MAURITANIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_MAURITIUS;
import static it.asansonne.storybe.constants.CountryNames.NAME_MAYOTTE;
import static it.asansonne.storybe.constants.CountryNames.NAME_MEXICO;
import static it.asansonne.storybe.constants.CountryNames.NAME_MICRONESIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_MONACO;
import static it.asansonne.storybe.constants.CountryNames.NAME_MONGOLIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_MONTSERRAT;
import static it.asansonne.storybe.constants.CountryNames.NAME_MOROCCO;
import static it.asansonne.storybe.constants.CountryNames.NAME_MOZAMBIQUE;
import static it.asansonne.storybe.constants.CountryNames.NAME_MYANMAR;
import static it.asansonne.storybe.constants.CountryNames.NAME_NAMIBIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_NAURU;
import static it.asansonne.storybe.constants.CountryNames.NAME_NEPAL;
import static it.asansonne.storybe.constants.CountryNames.NAME_NETHERLANDS;
import static it.asansonne.storybe.constants.CountryNames.NAME_NETHERLANDS_ANTILLES;
import static it.asansonne.storybe.constants.CountryNames.NAME_NEW_ZEALAND;
import static it.asansonne.storybe.constants.CountryNames.NAME_NICARAGUA;
import static it.asansonne.storybe.constants.CountryNames.NAME_NIGER;
import static it.asansonne.storybe.constants.CountryNames.NAME_NIGERIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_NIUE;
import static it.asansonne.storybe.constants.CountryNames.NAME_NORFOLK_ISLAND;
import static it.asansonne.storybe.constants.CountryNames.NAME_NORTHERN_MARIANA_ISLANDS;
import static it.asansonne.storybe.constants.CountryNames.NAME_NORTH_KOREA;
import static it.asansonne.storybe.constants.CountryNames.NAME_NORWAY;
import static it.asansonne.storybe.constants.CountryNames.NAME_OMAN;
import static it.asansonne.storybe.constants.CountryNames.NAME_PAKISTAN;
import static it.asansonne.storybe.constants.CountryNames.NAME_PALAU;
import static it.asansonne.storybe.constants.CountryNames.NAME_PANAMA;
import static it.asansonne.storybe.constants.CountryNames.NAME_PAPUA_NEW_GUINEA;
import static it.asansonne.storybe.constants.CountryNames.NAME_PARAGUAY;
import static it.asansonne.storybe.constants.CountryNames.NAME_PERU;
import static it.asansonne.storybe.constants.CountryNames.NAME_PHILIPPINES;
import static it.asansonne.storybe.constants.CountryNames.NAME_PITCAIRN_ISLAND;
import static it.asansonne.storybe.constants.CountryNames.NAME_POLAND;
import static it.asansonne.storybe.constants.CountryNames.NAME_PORTUGAL;
import static it.asansonne.storybe.constants.CountryNames.NAME_PUERTO_RICO;
import static it.asansonne.storybe.constants.CountryNames.NAME_QATAR;
import static it.asansonne.storybe.constants.CountryNames.NAME_ROMANIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_RUSSIAN_FEDERATION;
import static it.asansonne.storybe.constants.CountryNames.NAME_RWANDA;
import static it.asansonne.storybe.constants.CountryNames.NAME_SAINT_HELENA;
import static it.asansonne.storybe.constants.CountryNames.NAME_SAINT_LUCIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_SAN_MARINO;
import static it.asansonne.storybe.constants.CountryNames.NAME_SAUDI_ARABIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_SENEGAL;
import static it.asansonne.storybe.constants.CountryNames.NAME_SEYCHELLES;
import static it.asansonne.storybe.constants.CountryNames.NAME_SIERRA_LEONE;
import static it.asansonne.storybe.constants.CountryNames.NAME_SINGAPORE;
import static it.asansonne.storybe.constants.CountryNames.NAME_SLOVAK_REPUBLIC;
import static it.asansonne.storybe.constants.CountryNames.NAME_SLOVENIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_SOLOMON_ISLANDS;
import static it.asansonne.storybe.constants.CountryNames.NAME_SOMALIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_SOUTH_AFRICA;
import static it.asansonne.storybe.constants.CountryNames.NAME_SOUTH_KOREA;
import static it.asansonne.storybe.constants.CountryNames.NAME_SPAIN;
import static it.asansonne.storybe.constants.CountryNames.NAME_SRI_LANKA;
import static it.asansonne.storybe.constants.CountryNames.NAME_SUDAN;
import static it.asansonne.storybe.constants.CountryNames.NAME_SURINAME;
import static it.asansonne.storybe.constants.CountryNames.NAME_SVALBARD_AND_JAN_MAYEN_ISLANDS;
import static it.asansonne.storybe.constants.CountryNames.NAME_SWAZILAND;
import static it.asansonne.storybe.constants.CountryNames.NAME_SWEDEN;
import static it.asansonne.storybe.constants.CountryNames.NAME_SWITZERLAND;
import static it.asansonne.storybe.constants.CountryNames.NAME_THAILAND;
import static it.asansonne.storybe.constants.CountryNames.NAME_TOGO;
import static it.asansonne.storybe.constants.CountryNames.NAME_TOKELAU;
import static it.asansonne.storybe.constants.CountryNames.NAME_TONGA;
import static it.asansonne.storybe.constants.CountryNames.NAME_TRINIDAD_AND_TOBAGO;
import static it.asansonne.storybe.constants.CountryNames.NAME_TUNISIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_TURKEY;
import static it.asansonne.storybe.constants.CountryNames.NAME_TURKMENISTAN;
import static it.asansonne.storybe.constants.CountryNames.NAME_TURKS_AND_CAICOS_ISLANDS;
import static it.asansonne.storybe.constants.CountryNames.NAME_TUVALU;
import static it.asansonne.storybe.constants.CountryNames.NAME_UGANDA;
import static it.asansonne.storybe.constants.CountryNames.NAME_UKRAINE;
import static it.asansonne.storybe.constants.CountryNames.NAME_UNITED_ARAB_EMIRATES;
import static it.asansonne.storybe.constants.CountryNames.NAME_UNITED_KINGDOM;
import static it.asansonne.storybe.constants.CountryNames.NAME_UNITED_STATES;
import static it.asansonne.storybe.constants.CountryNames.NAME_URUGUAY;
import static it.asansonne.storybe.constants.CountryNames.NAME_UZBEKISTAN;
import static it.asansonne.storybe.constants.CountryNames.NAME_VANUATU;
import static it.asansonne.storybe.constants.CountryNames.NAME_VENEZUELA;
import static it.asansonne.storybe.constants.CountryNames.NAME_VIRGIN_ISLANDS_BRITISH;
import static it.asansonne.storybe.constants.CountryNames.NAME_WALLIS_AND_FUTUNA_ISLANDS;
import static it.asansonne.storybe.constants.CountryNames.NAME_WESTERN_SAHARA;
import static it.asansonne.storybe.constants.CountryNames.NAME_YEMEN;
import static it.asansonne.storybe.constants.CountryNames.NAME_YUGOSLAVIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_ZAMBIA;
import static it.asansonne.storybe.constants.CountryNames.NAME_ZIMBABWE;

import java.util.HashMap;
import java.util.Map;

public class Country {
  private final Map<String, String> map;

  public Country() {
    map = new HashMap<>();
    map.put(NAME_ANDORRA_PRINCIPALITY_OF.getRole(), CODE_ANDORRA_PRINCIPALITY_OF.getRole());
    map.put(NAME_UNITED_ARAB_EMIRATES.getRole(), CODE_UNITED_ARAB_EMIRATES.getRole());
    map.put(NAME_AFGHANISTAN_ISLAMIC_STATE_OF.getRole(),
        CODE_AFGHANISTAN_ISLAMIC_STATE_OF.getRole());
    map.put(NAME_ANTIGUA_AND_BARBUDA.getRole(), CODE_ANTIGUA_AND_BARBUDA.getRole());
    map.put(NAME_ANGUILLA.getRole(), CODE_ANGUILLA.getRole());
    map.put(NAME_ALBANIA.getRole(), CODE_ALBANIA.getRole());
    map.put(NAME_ARMENIA.getRole(), CODE_ARMENIA.getRole());
    map.put(NAME_NETHERLANDS_ANTILLES.getRole(), CODE_NETHERLANDS_ANTILLES.getRole());
    map.put(NAME_ANGOLA.getRole(), CODE_ANGOLA.getRole());
    map.put(NAME_ANTARCTICA.getRole(), CODE_ANTARCTICA.getRole());
    map.put(NAME_ARGENTINA.getRole(), CODE_ARGENTINA.getRole());
    map.put(NAME_AMERICAN_SAMOA.getRole(), CODE_AMERICAN_SAMOA.getRole());
    map.put(NAME_AUSTRIA.getRole(), CODE_AUSTRIA.getRole());
    map.put(NAME_AUSTRALIA.getRole(), CODE_AUSTRALIA.getRole());
    map.put(NAME_ARUBA.getRole(), CODE_ARUBA.getRole());
    map.put(NAME_AZERBAIDJAN.getRole(), CODE_AZERBAIDJAN.getRole());
    map.put(NAME_BOSNIA_HERZEGOVINA.getRole(), CODE_BOSNIA_HERZEGOVINA.getRole());
    map.put(NAME_BARBADOS.getRole(), CODE_BARBADOS.getRole());
    map.put(NAME_BANGLADESH.getRole(), CODE_BANGLADESH.getRole());
    map.put(NAME_BELGIUM.getRole(), CODE_BELGIUM.getRole());
    map.put(NAME_BURKINA_FASO.getRole(), CODE_BURKINA_FASO.getRole());
    map.put(NAME_BULGARIA.getRole(), CODE_BULGARIA.getRole());
    map.put(NAME_BAHRAIN.getRole(), CODE_BAHRAIN.getRole());
    map.put(NAME_BURUNDI.getRole(), CODE_BURUNDI.getRole());
    map.put(NAME_BENIN.getRole(), CODE_BENIN.getRole());
    map.put(NAME_BERMUDA.getRole(), CODE_BERMUDA.getRole());
    map.put(NAME_BRUNEI_DARUSSALAM.getRole(), CODE_BRUNEI_DARUSSALAM.getRole());
    map.put(NAME_BOLIVIA.getRole(), CODE_BOLIVIA.getRole());
    map.put(NAME_BRAZIL.getRole(), CODE_BRAZIL.getRole());
    map.put(NAME_BAHAMAS.getRole(), CODE_BAHAMAS.getRole());
    map.put(NAME_BHUTAN.getRole(), CODE_BHUTAN.getRole());
    map.put(NAME_BOUVET_ISLAND.getRole(), CODE_BOUVET_ISLAND.getRole());
    map.put(NAME_BOTSWANA.getRole(), CODE_BOTSWANA.getRole());
    map.put(NAME_BELARUS.getRole(), CODE_BELARUS.getRole());
    map.put(NAME_BELIZE.getRole(), CODE_BELIZE.getRole());
    map.put(NAME_CANADA.getRole(), CODE_CANADA.getRole());
    map.put(NAME_COCOS_KEELING_ISLANDS.getRole(), CODE_COCOS_KEELING_ISLANDS.getRole());
    map.put(NAME_CENTRAL_AFRICAN_REPUBLIC.getRole(), CODE_CENTRAL_AFRICAN_REPUBLIC.getRole());
    map.put(NAME_CONGO_DEMOCRATIC_REPUBLIC_OF_THE.getRole(),
        CODE_CONGO_DEMOCRATIC_REPUBLIC_OF_THE.getRole());
    map.put(NAME_CONGO.getRole(), CODE_CONGO.getRole());
    map.put(NAME_SWITZERLAND.getRole(), CODE_SWITZERLAND.getRole());
    map.put(NAME_IVORY_COAST_COTE_D_IVOIRE.getRole(), CODE_IVORY_COAST_COTE_D_IVOIRE.getRole());
    map.put(NAME_COOK_ISLANDS.getRole(), CODE_COOK_ISLANDS.getRole());
    map.put(NAME_CHILE.getRole(), CODE_CHILE.getRole());
    map.put(NAME_CAMEROON.getRole(), CODE_CAMEROON.getRole());
    map.put(NAME_CHINA.getRole(), CODE_CHINA.getRole());
    map.put(NAME_COLOMBIA.getRole(), CODE_COLOMBIA.getRole());
    map.put(NAME_COSTA_RICA.getRole(), CODE_COSTA_RICA.getRole());
    map.put(NAME_FORMER_CZECHOSLOVAKIA.getRole(), CODE_FORMER_CZECHOSLOVAKIA.getRole());
    map.put(NAME_CUBA.getRole(), CODE_CUBA.getRole());
    map.put(NAME_CAPE_VERDE.getRole(), CODE_CAPE_VERDE.getRole());
    map.put(NAME_CHRISTMAS_ISLAND.getRole(), CODE_CHRISTMAS_ISLAND.getRole());
    map.put(NAME_CYPRUS.getRole(), CODE_CYPRUS.getRole());
    map.put(NAME_CZECH_REPUBLIC.getRole(), CODE_CZECH_REPUBLIC.getRole());
    map.put(NAME_GERMANY.getRole(), CODE_GERMANY.getRole());
    map.put(NAME_DJIBOUTI.getRole(), CODE_DJIBOUTI.getRole());
    map.put(NAME_DENMARK.getRole(), CODE_DENMARK.getRole());
    map.put(NAME_DOMINICA.getRole(), CODE_DOMINICA.getRole());
    map.put(NAME_DOMINICAN_REPUBLIC.getRole(), CODE_DOMINICAN_REPUBLIC.getRole());
    map.put(NAME_ALGERIA.getRole(), CODE_ALGERIA.getRole());
    map.put(NAME_ECUADOR.getRole(), CODE_ECUADOR.getRole());
    map.put(NAME_ESTONIA.getRole(), CODE_ESTONIA.getRole());
    map.put(NAME_EGYPT.getRole(), CODE_EGYPT.getRole());
    map.put(NAME_WESTERN_SAHARA.getRole(), CODE_WESTERN_SAHARA.getRole());
    map.put(NAME_ERITREA.getRole(), CODE_ERITREA.getRole());
    map.put(NAME_SPAIN.getRole(), CODE_SPAIN.getRole());
    map.put(NAME_ETHIOPIA.getRole(), CODE_ETHIOPIA.getRole());
    map.put(NAME_FINLAND.getRole(), CODE_FINLAND.getRole());
    map.put(NAME_FIJI.getRole(), CODE_FIJI.getRole());
    map.put(NAME_FALKLAND_ISLANDS.getRole(), CODE_FALKLAND_ISLANDS.getRole());
    map.put(NAME_MICRONESIA.getRole(), CODE_MICRONESIA.getRole());
    map.put(NAME_FAROE_ISLANDS.getRole(), CODE_FAROE_ISLANDS.getRole());
    map.put(NAME_FRANCE.getRole(), CODE_FRANCE.getRole());
    map.put(NAME_FRANCE_EUROPEAN_TERRITORY.getRole(), CODE_FRANCE_EUROPEAN_TERRITORY.getRole());
    map.put(NAME_GABON.getRole(), CODE_GABON.getRole());
    map.put(NAME_GREAT_BRITAIN.getRole(), CODE_GREAT_BRITAIN.getRole());
    map.put(NAME_GRENADA.getRole(), CODE_GRENADA.getRole());
    map.put(NAME_GEORGIA.getRole(), CODE_GEORGIA.getRole());
    map.put(NAME_GHANA.getRole(), CODE_GHANA.getRole());
    map.put(NAME_GIBRALTAR.getRole(), CODE_GIBRALTAR.getRole());
    map.put(NAME_GREENLAND.getRole(), CODE_GREENLAND.getRole());
    map.put(NAME_GAMBIA.getRole(), CODE_GAMBIA.getRole());
    map.put(NAME_GUINEA.getRole(), CODE_GUINEA.getRole());
    map.put(NAME_EQUATORIAL_GUINEA.getRole(), CODE_EQUATORIAL_GUINEA.getRole());
    map.put(NAME_GREECE.getRole(), CODE_GREECE.getRole());
    map.put(NAME_GUATEMALA.getRole(), CODE_GUATEMALA.getRole());
    map.put(NAME_GUINEA_BISSAU.getRole(), CODE_GUINEA_BISSAU.getRole());
    map.put(NAME_GUYANA.getRole(), CODE_GUYANA.getRole());
    map.put(NAME_HONG_KONG.getRole(), CODE_HONG_KONG.getRole());
    map.put(NAME_HONDURAS.getRole(), CODE_HONDURAS.getRole());
    map.put(NAME_CROATIA.getRole(), CODE_CROATIA.getRole());
    map.put(NAME_HAITI.getRole(), CODE_HAITI.getRole());
    map.put(NAME_HUNGARY.getRole(), CODE_HUNGARY.getRole());
    map.put(NAME_INDONESIA.getRole(), CODE_INDONESIA.getRole());
    map.put(NAME_INDIA.getRole(), CODE_INDIA.getRole());
    map.put(NAME_BRITISH_INDIAN_OCEAN_TERRITORY.getRole(),
        CODE_BRITISH_INDIAN_OCEAN_TERRITORY.getRole());
    map.put(NAME_IRELAND.getRole(), CODE_IRELAND.getRole());
    map.put(NAME_IRAQ.getRole(), CODE_IRAQ.getRole());
    map.put(NAME_ICELAND.getRole(), CODE_ICELAND.getRole());
    map.put(NAME_ISRAEL.getRole(), CODE_ISRAEL.getRole());
    map.put(NAME_ITALY.getRole(), CODE_ITALY.getRole());
    map.put(NAME_JAMAICA.getRole(), CODE_JAMAICA.getRole());
    map.put(NAME_JORDAN.getRole(), CODE_JORDAN.getRole());
    map.put(NAME_JAPAN.getRole(), CODE_JAPAN.getRole());
    map.put(NAME_KENYA.getRole(), CODE_KENYA.getRole());
    map.put(NAME_KIRIBATI.getRole(), CODE_KIRIBATI.getRole());
    map.put(NAME_COMOROS.getRole(), CODE_COMOROS.getRole());
    map.put(NAME_NORTH_KOREA.getRole(), CODE_NORTH_KOREA.getRole());
    map.put(NAME_SOUTH_KOREA.getRole(), CODE_SOUTH_KOREA.getRole());
    map.put(NAME_KUWAIT.getRole(), CODE_KUWAIT.getRole());
    map.put(NAME_CAYMAN_ISLANDS.getRole(), CODE_CAYMAN_ISLANDS.getRole());
    map.put(NAME_KAZAKHSTAN.getRole(), CODE_KAZAKHSTAN.getRole());
    map.put(NAME_LEBANON.getRole(), CODE_LEBANON.getRole());
    map.put(NAME_SAINT_LUCIA.getRole(), CODE_SAINT_LUCIA.getRole());
    map.put(NAME_LIECHTENSTEIN.getRole(), CODE_LIECHTENSTEIN.getRole());
    map.put(NAME_SRI_LANKA.getRole(), CODE_SRI_LANKA.getRole());
    map.put(NAME_LIBERIA.getRole(), CODE_LIBERIA.getRole());
    map.put(NAME_LESOTHO.getRole(), CODE_LESOTHO.getRole());
    map.put(NAME_LITHUANIA.getRole(), CODE_LITHUANIA.getRole());
    map.put(NAME_LUXEMBOURG.getRole(), CODE_LUXEMBOURG.getRole());
    map.put(NAME_LATVIA.getRole(), CODE_LATVIA.getRole());
    map.put(NAME_MOROCCO.getRole(), CODE_MOROCCO.getRole());
    map.put(NAME_MONACO.getRole(), CODE_MONACO.getRole());
    map.put(NAME_MADAGASCAR.getRole(), CODE_MADAGASCAR.getRole());
    map.put(NAME_MARSHALL_ISLANDS.getRole(), CODE_MARSHALL_ISLANDS.getRole());
    map.put(NAME_MALI.getRole(), CODE_MALI.getRole());
    map.put(NAME_MYANMAR.getRole(), CODE_MYANMAR.getRole());
    map.put(NAME_MONGOLIA.getRole(), CODE_MONGOLIA.getRole());
    map.put(NAME_MACAU.getRole(), CODE_MACAU.getRole());
    map.put(NAME_NORTHERN_MARIANA_ISLANDS.getRole(), CODE_NORTHERN_MARIANA_ISLANDS.getRole());
    map.put(NAME_MAURITANIA.getRole(), CODE_MAURITANIA.getRole());
    map.put(NAME_MONTSERRAT.getRole(), CODE_MONTSERRAT.getRole());
    map.put(NAME_MALTA.getRole(), CODE_MALTA.getRole());
    map.put(NAME_MAURITIUS.getRole(), CODE_MAURITIUS.getRole());
    map.put(NAME_MALDIVES.getRole(), CODE_MALDIVES.getRole());
    map.put(NAME_MALAWI.getRole(), CODE_MALAWI.getRole());
    map.put(NAME_MEXICO.getRole(), CODE_MEXICO.getRole());
    map.put(NAME_MALAYSIA.getRole(), CODE_MALAYSIA.getRole());
    map.put(NAME_MOZAMBIQUE.getRole(), CODE_MOZAMBIQUE.getRole());
    map.put(NAME_NAMIBIA.getRole(), CODE_NAMIBIA.getRole());
    map.put(NAME_NIGER.getRole(), CODE_NIGER.getRole());
    map.put(NAME_NORFOLK_ISLAND.getRole(), CODE_NORFOLK_ISLAND.getRole());
    map.put(NAME_NIGERIA.getRole(), CODE_NIGERIA.getRole());
    map.put(NAME_NICARAGUA.getRole(), CODE_NICARAGUA.getRole());
    map.put(NAME_NETHERLANDS.getRole(), CODE_NETHERLANDS.getRole());
    map.put(NAME_NORWAY.getRole(), CODE_NORWAY.getRole());
    map.put(NAME_NEPAL.getRole(), CODE_NEPAL.getRole());
    map.put(NAME_NAURU.getRole(), CODE_NAURU.getRole());
    map.put(NAME_NIUE.getRole(), CODE_NIUE.getRole());
    map.put(NAME_NEW_ZEALAND.getRole(), CODE_NEW_ZEALAND.getRole());
    map.put(NAME_OMAN.getRole(), CODE_OMAN.getRole());
    map.put(NAME_PANAMA.getRole(), CODE_PANAMA.getRole());
    map.put(NAME_PERU.getRole(), CODE_PERU.getRole());
    map.put(NAME_PAPUA_NEW_GUINEA.getRole(), CODE_PAPUA_NEW_GUINEA.getRole());
    map.put(NAME_PHILIPPINES.getRole(), CODE_PHILIPPINES.getRole());
    map.put(NAME_PAKISTAN.getRole(), CODE_PAKISTAN.getRole());
    map.put(NAME_POLAND.getRole(), CODE_POLAND.getRole());
    map.put(NAME_PITCAIRN_ISLAND.getRole(), CODE_PITCAIRN_ISLAND.getRole());
    map.put(NAME_PUERTO_RICO.getRole(), CODE_PUERTO_RICO.getRole());
    map.put(NAME_PORTUGAL.getRole(), CODE_PORTUGAL.getRole());
    map.put(NAME_PALAU.getRole(), CODE_PALAU.getRole());
    map.put(NAME_PARAGUAY.getRole(), CODE_PARAGUAY.getRole());
    map.put(NAME_QATAR.getRole(), CODE_QATAR.getRole());
    map.put(NAME_ROMANIA.getRole(), CODE_ROMANIA.getRole());
    map.put(NAME_RUSSIAN_FEDERATION.getRole(), CODE_RUSSIAN_FEDERATION.getRole());
    map.put(NAME_RWANDA.getRole(), CODE_RWANDA.getRole());
    map.put(NAME_SAUDI_ARABIA.getRole(), CODE_SAUDI_ARABIA.getRole());
    map.put(NAME_SOLOMON_ISLANDS.getRole(), CODE_SOLOMON_ISLANDS.getRole());
    map.put(NAME_SEYCHELLES.getRole(), CODE_SEYCHELLES.getRole());
    map.put(NAME_SUDAN.getRole(), CODE_SUDAN.getRole());
    map.put(NAME_SWEDEN.getRole(), CODE_SWEDEN.getRole());
    map.put(NAME_SINGAPORE.getRole(), CODE_SINGAPORE.getRole());
    map.put(NAME_SAINT_HELENA.getRole(), CODE_SAINT_HELENA.getRole());
    map.put(NAME_SLOVENIA.getRole(), CODE_SLOVENIA.getRole());
    map.put(NAME_SVALBARD_AND_JAN_MAYEN_ISLANDS.getRole(),
        CODE_SVALBARD_AND_JAN_MAYEN_ISLANDS.getRole());
    map.put(NAME_SLOVAK_REPUBLIC.getRole(), CODE_SLOVAK_REPUBLIC.getRole());
    map.put(NAME_SIERRA_LEONE.getRole(), CODE_SIERRA_LEONE.getRole());
    map.put(NAME_SAN_MARINO.getRole(), CODE_SAN_MARINO.getRole());
    map.put(NAME_SENEGAL.getRole(), CODE_SENEGAL.getRole());
    map.put(NAME_SOMALIA.getRole(), CODE_SOMALIA.getRole());
    map.put(NAME_SURINAME.getRole(), CODE_SURINAME.getRole());
    map.put(NAME_EL_SALVADOR.getRole(), CODE_EL_SALVADOR.getRole());
    map.put(NAME_SWAZILAND.getRole(), CODE_SWAZILAND.getRole());
    map.put(NAME_TURKS_AND_CAICOS_ISLANDS.getRole(), CODE_TURKS_AND_CAICOS_ISLANDS.getRole());
    map.put(NAME_CHAD.getRole(), CODE_CHAD.getRole());
    map.put(NAME_FRENCH_SOUTHERN_TERRITORIES.getRole(), CODE_FRENCH_SOUTHERN_TERRITORIES.getRole());
    map.put(NAME_TOGO.getRole(), CODE_TOGO.getRole());
    map.put(NAME_THAILAND.getRole(), CODE_THAILAND.getRole());
    map.put(NAME_TOKELAU.getRole(), CODE_TOKELAU.getRole());
    map.put(NAME_TURKMENISTAN.getRole(), CODE_TURKMENISTAN.getRole());
    map.put(NAME_TUNISIA.getRole(), CODE_TUNISIA.getRole());
    map.put(NAME_TONGA.getRole(), CODE_TONGA.getRole());
    map.put(NAME_EAST_TIMOR.getRole(), CODE_EAST_TIMOR.getRole());
    map.put(NAME_TURKEY.getRole(), CODE_TURKEY.getRole());
    map.put(NAME_TRINIDAD_AND_TOBAGO.getRole(), CODE_TRINIDAD_AND_TOBAGO.getRole());
    map.put(NAME_TUVALU.getRole(), CODE_TUVALU.getRole());
    map.put(NAME_UKRAINE.getRole(), CODE_UKRAINE.getRole());
    map.put(NAME_UGANDA.getRole(), CODE_UGANDA.getRole());
    map.put(NAME_UNITED_KINGDOM.getRole(), CODE_UNITED_KINGDOM.getRole());
    map.put(NAME_UNITED_STATES.getRole(), CODE_UNITED_STATES.getRole());
    map.put(NAME_URUGUAY.getRole(), CODE_URUGUAY.getRole());
    map.put(NAME_UZBEKISTAN.getRole(), CODE_UZBEKISTAN.getRole());
    map.put(NAME_VENEZUELA.getRole(), CODE_VENEZUELA.getRole());
    map.put(NAME_VIRGIN_ISLANDS_BRITISH.getRole(), CODE_VIRGIN_ISLANDS_BRITISH.getRole());
    map.put(NAME_VANUATU.getRole(), CODE_VANUATU.getRole());
    map.put(NAME_WALLIS_AND_FUTUNA_ISLANDS.getRole(), CODE_WALLIS_AND_FUTUNA_ISLANDS.getRole());
    map.put(NAME_WESTERN_SAHARA.getRole(), CODE_WESTERN_SAHARA.getRole());
    map.put(NAME_YEMEN.getRole(), CODE_YEMEN.getRole());
    map.put(NAME_MAYOTTE.getRole(), CODE_MAYOTTE.getRole());
    map.put(NAME_YUGOSLAVIA.getRole(), CODE_YUGOSLAVIA.getRole());
    map.put(NAME_SOUTH_AFRICA.getRole(), CODE_SOUTH_AFRICA.getRole());
    map.put(NAME_ZAMBIA.getRole(), CODE_ZAMBIA.getRole());
    map.put(NAME_ZIMBABWE.getRole(), CODE_ZIMBABWE.getRole());
  }

  public String getName(String country) {
    String countryFound = map.get(country);
    if (countryFound == null) {
      countryFound = "Italy";
    }
    return countryFound;
  }

  public String getCode(String country) {
    String countryFound = map.get(country);
    if (countryFound == null) {
      countryFound = "IT";
    }
    return countryFound;
  }

}


