package it.asansonne.storybe.constants;

import lombok.Getter;

@Getter
public enum JobPosition {
	SOFTWARE_DEVELOPER ("SOFTWARE_DEVELOPER"),
	FRONTEND_DEVELOPER ("FRONTEND_DEVELOPER"),
	BACKEND_DEVELOPER ("BACKEND_DEVELOPER"),
	FULLSTACK_DEVELOPER ("FULLSTACK_DEVELOPER"),
	DEVOPS_ENGINEER ("DEVOPS_ENGINEER"),
	DATA_SCIENTIST ("DATA_SCIENTIST"),
	DATA_ENGINEER ("DATA_ENGINEER"),
	MACHINE_LEARNING_ENGINEER ("MACHINE_LEARNING_ENGINEER"),
	DATABASE_ADMINISTRATOR ("DATABASE_ADMINISTRATOR"),
	SYSTEM_ADMINISTRATOR ("SYSTEM_ADMINISTRATOR"),
	NETWORK_ENGINEER ("NETWORK_ENGINEER"),
	CLOUD_ENGINEER ("CLOUD_ENGINEER"),
	QA_ENGINEER ("QA_ENGINEER"),
	BUSINESS_ANALYST ("BUSINESS_ANALYST"),
	PRODUCT_MANAGER ("PRODUCT_MANAGER"),
	PROJECT_MANAGER ("PROJECT_MANAGER"),
	SCRUM_MASTER ("SCRUM_MASTER"),
	SOFTWARE_ARCHITECT ("SOFTWARE_ARCHITECT"),
	SECURITY_ANALYST ("SECURITY_ANALYST"),
	MOBILE_DEVELOPER ("MOBILE_DEVELOPER"),
	UI_UX_DESIGNER ("UI_UX_DESIGNER"),
	TECHNICAL_SUPPORT_SPECIALIST ("TECHNICAL_SUPPORT_SPECIALIST"),
	IT_MANAGER ("IT_MANAGER"),
	IT_DIRECTOR ("IT_DIRECTOR"),
	CTO ("CTO");

	private final String role;

	JobPosition(String role){
		this.role = role;
	}
}